### ISSUE TITLE
Invalid sample format '(null)' Error opening filters when converting blob with multiple streams

### ISSUE THREAD

**Issue by cviali** [muaz-khan/Ffmpeg.js#18]
Looks like someone asked the same question back in 2017 [here's](https://stackoverflow.com/questions/46752262/recording-html5-canvas-animation-in-mp4-format)
 the link.
I used [this](https://www.webrtc-experiment.com/RecordRTC/Canvas-Recording/Canvas-Animation-Recording-Plus-Microphone.html) method of recording canvas with microphone and pack it in a single .webm .

But, using [this](https://www.webrtc-experiment.com/ffmpeg/webm-to-mp4.html) method, I tried to record the .webm created from method above but it throws `Invalid sample format '(null)' Error opening filters.`

Is there any additional ffmpeg configurations I need to do beforehand? did I miss something?

**EDIT**: I've tried to turn off the audio stream, turns out it works fine. Is there any workaround to this?
**EDIT2**: Looks like this is have the same issue as issue #12  .

**Comment by onehassan** [comment]
I am facing the same issue, have you been able to solve it?

**Comment by cviali** [comment]
Nope, I might try out some alternatives such as recording both wav and webm, then merge it with ffmpeg.

**Comment by cviali** [comment]
> I am facing the same issue, have you been able to solve it?

Hi, just wanna update on you that I've finally able to convert .webm with audio channel through FFMpeg-PHP, doing it server side on my controller.

https://github.com/PHP-FFMpeg/PHP-FFMpeg

**Comment by yutou15** [comment]
solve it by updating ffmpeg version. try this one: https://github.com/x213212/build_ffmpeg.js
